[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps = adafruit/Adafruit Motor Shield library@^1.0.1
build_flags = -DARDUINO_AVR_UNO
monitor_speed = 115200
