[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
    arduino-libraries/Servo@^1.2.2
build_flags =
    -DARDUINO_AVR_UNO
    -DCAMERA_SERVO_PIN=3
monitor_speed = 115200